# lightning.pytorch==2.2.1
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
    # class_path: lightning.pytorch.strategies.DDPStrategy
    # dict_kwargs:
    #   broadcast_buffers: false
    #   find_unused_parameters: true
  devices: auto
  num_nodes: 1
  precision: 32
  logger: null
  callbacks: 
  - class_path: cellarium.ml.callbacks.PredictionWriter
    init_args:
      output_dir: /home/sfleming/cellarium-ml/examples/cli_workflow/scvi_big_run/predictions
      prediction_size: null
  fast_dev_run: false
  max_epochs: 1
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: null
  num_sanity_val_steps: null
  log_every_n_steps: 1
  enable_checkpointing: true
  enable_progress_bar: true
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: 0.5
  gradient_clip_algorithm: norm
  deterministic: null
  benchmark: null
  inference_mode: false
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: null
model:
  cpu_transforms:
    - class_path: cellarium.ml.transforms.Filter
      init_args:
        filter_list:
          !FileLoader
          file_path: /home/sfleming/cellarium-ml/examples/cli_workflow/scvi_big_run/hvg_plus_glyco_genes_20241216.txt
          loader_fn: pandas.read_csv
          attr: "ensembl_id"
          convert_fn: pandas.Series.to_list
  model:
    class_path: cellarium.ml.models.SingleCellVariationalInference
    init_args:
      # these are pulled from data, leave null
      var_names_g: null
      n_batch: null
      # these can be changed
      batch_embedded: true
      batch_representation_sampled: true
      n_latent_batch: null
      batch_kl_weight: 0.01
      encoder: 
        hidden_layers:
        - class_path: cellarium.ml.models.scvi.LinearWithBatch
          init_args:
            out_features: 128
            batch_to_bias_hidden_layers: []  # one linear transformation: what scvi-tools does
        final_layer:
          class_path: torch.nn.Linear
          init_args: {}
      decoder:
        hidden_layers:
        - class_path: cellarium.ml.models.scvi.LinearWithBatch
          init_args:
            out_features: 128
            batch_to_bias_hidden_layers: []
              # hidden_layers:
              # - class_path: torch.nn.Linear
              #     init_args:
              #       out_features: 10
              # - class_path: torch.nn.Linear
              #     init_args:
              #       out_features: 20
        final_layer: 
          class_path: cellarium.ml.models.scvi.LinearWithBatch
          init_args:
            batch_to_bias_hidden_layers: []
        final_additive_bias: true
      n_latent: 50
      # probably leave these alone
      n_continuous_cov: 0
      n_cats_per_cov: null
      dropout_rate: 0.1
      dispersion: gene
      log_variational: true
      gene_likelihood: nb
      latent_distribution: normal
      use_batch_norm: both
      use_layer_norm: none
      use_size_factor_key: false
      use_observed_lib_size: true
  optim_fn: torch.optim.AdamW
  optim_kwargs: 
    lr: 1e-4
  scheduler_fn: null
  scheduler_kwargs: null
  is_initialized: False
data:
  dadc:
    class_path: cellarium.ml.data.DistributedAnnDataCollection
    init_args:
      filenames: gs://cellarium-human-primary-data/curriculum/human_all_primary_20241108/extract_files/extract_{0..4440}.h5ad
      limits: null
      shard_size: 10_000
      last_shard_size: 6428
      max_cache_size: 2
      cache_size_strictly_enforced: true
      label: null
      keys: null
      index_unique: null
      convert: null
      indices_strict: true
      obs_columns_to_validate: []
        # - donor_dataset_concat
        # - suspension_type
        # - assay
  batch_keys:
    x_ng:
      attr: X
      convert_fn: cellarium.ml.utilities.data.densify
    obs_names_n:
      attr: obs_names
    var_names_g:
      attr: var_names
    batch_index_n:
      attr: obs
      key: donor_dataset_concat
      convert_fn: cellarium.ml.utilities.data.categories_to_codes
    categorical_covariate_index_nd:
      attr: obs
      key: 
        - suspension_type
        - assay
      convert_fn: cellarium.ml.utilities.data.categories_to_codes
  batch_size: 4096
  shuffle: false
  # seed: 0
  # drop_last: false
  test_mode: false
  num_workers: 8
  prefetch_factor: null
  persistent_workers: true
ckpt_path: /home/sfleming/cellarium-ml/examples/cli_workflow/scvi_big_run/lightning_logs/version_17/checkpoints/epoch=2-step=250000.ckpt
return_predictions: false
