# lightning.pytorch==2.5.2
seed_everything: true
trainer:
  accelerator: auto
  strategy: auto
  devices: 1
  num_nodes: 1
  precision: 32
  logger: null
  callbacks: 
  - class_path: lightning.pytorch.callbacks.TQDMProgressBar
    init_args:
      refresh_rate: 100
      leave: true
  - class_path: lightning.pytorch.callbacks.ModelCheckpoint
    init_args:
      save_last: true  # Always save the last checkpoint
      save_on_train_epoch_end: true  # Save at end of each epoch
      every_n_epochs: null
      every_n_train_steps: null
      save_top_k: -1
  max_epochs: 100
  log_every_n_steps: 100
  enable_checkpointing: true
  enable_progress_bar: true
  accumulate_grad_batches: 1
  gradient_clip_val: 50
  gradient_clip_algorithm: norm
  deterministic: null
  benchmark: null
  inference_mode: false
  use_distributed_sampler: true
  detect_anomaly: false
  sync_batchnorm: false
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: /home/sfleming/scvi_runs
model:
  cpu_transforms:
    - class_path: cellarium.ml.transforms.Filter
      init_args:
        filter_list:
          !FileLoader
          file_path: /home/sfleming/scvi_runs/all_training_genes_hvg_plus_glyco_20241216.txt
          loader_fn: pandas.read_csv
          attr: "ensembl_id"
          convert_fn: pandas.Series.to_list

  model:
    class_path: cellarium.ml.models.SingleCellVariationalInference
    init_args:

      # these are pulled from data, leave null
      var_names_g: null
      n_batch: null

      # these can be changed
      batch_embedded: false
      batch_representation_sampled: false
      n_latent_batch: null
      batch_kl_weight_max: 0.0
      kl_warmup_epochs: 20
      kl_annealing_start: 0.0
      z_kl_weight_max: 1.0
      encoder: 
        hidden_layers:
        # - class_path: cellarium.ml.models.scvi.LinearWithBatch
        - class_path: torch.nn.Linear
          init_args:
            out_features: 128
            # batch_to_bias_hidden_layers: []  # one linear transformation: what scvi-tools does
        # - class_path: cellarium.ml.models.scvi.LinearWithBatch
        - class_path: torch.nn.Linear
          init_args:
            out_features: 128
            # batch_to_bias_hidden_layers: []
        final_layer:
          class_path: torch.nn.Linear
          init_args: {}
      decoder:
        hidden_layers:
        - class_path: cellarium.ml.models.scvi.LinearWithBatch
          init_args:
            out_features: 128
            batch_to_bias_hidden_layers: []
        - class_path: cellarium.ml.models.scvi.LinearWithBatch
          init_args:
            out_features: 128
            batch_to_bias_hidden_layers: []
        final_layer: 
          class_path: torch.nn.Linear
          init_args: {}
        final_additive_bias: false
      n_latent: 50

      # probably leave these alone
      n_continuous_cov: 0
      n_cats_per_cov: null
      dropout_rate: 0.1
      dispersion: gene
      log_variational: true
      gene_likelihood: nb
      latent_distribution: normal
      use_batch_norm: both
      use_layer_norm: none
      use_size_factor_key: false
      use_observed_lib_size: true
  optim_fn: torch.optim.Adam
  optim_kwargs: 
    lr: 1e-4
    weight_decay: 1e-6
    eps: 0.01
  scheduler_fn: null
  scheduler_kwargs: null
  is_initialized: false
data:
  dadc:
    class_path: cellarium.ml.data.DistributedAnnDataCollection
    init_args:
      filenames: /local/path/to/extract_{0..4440}_subset.h5ad
      limits: null
      shard_size: 10_000
      last_shard_size: 6428
      max_cache_size: 3
      cache_size_strictly_enforced: true
      label: null
      keys: null
      index_unique: null
      convert: null
      indices_strict: true
      obs_columns_to_validate: []
        # - donor_dataset_concat
        # - suspension_type
        # - assay
  batch_keys:
    x_ng:
      attr: X
      convert_fn: cellarium.ml.utilities.data.densify
    var_names_g:
      attr: var_names
    batch_index_n:
      attr: obs
      key: donor_dataset_concat
      convert_fn: cellarium.ml.utilities.data.categories_to_codes
    #categorical_covariate_index_nd:
    #  attr: obs
    #  key: 
    #    - suspension_type
    #    - assay
    #  convert_fn: cellarium.ml.utilities.data.categories_to_codes
  batch_size: 1024
  iteration_strategy: cache_efficient
  shuffle: true
  shuffle_seed: 0
  drop_last_indices: false
  drop_incomplete_batch: false
  worker_seed: null
  test_mode: false
  num_workers: 14
  prefetch_factor: 3
  persistent_workers: true
ckpt_path: null